"""
MongoDB Data Models
Pydantic models for MongoDB document structure
"""
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


def generate_uuid() -> str:
    """Generate UUID4 string"""
    return str(uuid.uuid4())


def utc_now() -> datetime:
    """Get current UTC timestamp"""
    return datetime.now(timezone.utc)


# ============================================================================
# USER & AUTHENTICATION MODELS
# ============================================================================


class User(BaseModel):
    """User accounts and authentication"""

    id: str = Field(default_factory=generate_uuid, alias="_id")
    username: str = Field(..., max_length=50)
    email: str = Field(..., max_length=255)
    password_hash: str = Field(..., max_length=255)
    full_name: Optional[str] = Field(None, max_length=100)
    phone: Optional[str] = Field(None, max_length=20)
    company: Optional[str] = Field(None, max_length=100)

    # Status
    is_active: bool = True
    is_admin: bool = False
    is_verified: bool = False

    # Timestamps
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)
    last_login: Optional[datetime] = None

    class Config:
        populate_by_name = True


class RefreshToken(BaseModel):
    """JWT refresh tokens for long-lived authentication"""

    id: Optional[str] = Field(default_factory=generate_uuid, alias="_id")
    token: str = Field(..., max_length=255)
    user_id: str

    # Expiration & Revocation
    expires_at: datetime
    is_revoked: bool = False
    revoked_at: Optional[datetime] = None
    revoked_reason: Optional[str] = Field(None, max_length=100)

    # Metadata
    created_at: datetime = Field(default_factory=utc_now)
    ip_address: Optional[str] = Field(None, max_length=45)
    user_agent: Optional[str] = Field(None, max_length=255)

    class Config:
        populate_by_name = True


# ============================================================================
# DESIGN SPECIFICATION MODELS
# ============================================================================


class Spec(BaseModel):
    """Design specifications generated by LM"""

    id: str = Field(default_factory=generate_uuid, alias="_id")
    user_id: str
    project_id: Optional[str] = None

    # Prompt & Generation
    prompt: str
    city: str = Field(..., max_length=50)
    spec_json: Dict[str, Any]
    design_type: Optional[str] = Field(None, max_length=50)

    # Preview & Storage
    preview_url: Optional[str] = Field(None, max_length=512)
    geometry_url: Optional[str] = Field(None, max_length=512)

    # Cost & Compliance
    estimated_cost: Optional[float] = None
    currency: str = "INR"
    compliance_status: str = "pending"

    # Status
    status: str = "draft"  # draft, final, archived, deleted
    version: int = 1

    # Metadata
    generation_time_ms: Optional[int] = None
    lm_provider: Optional[str] = None

    # Timestamps
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)

    class Config:
        populate_by_name = True


class Iteration(BaseModel):
    """Material/property changes to specs"""

    id: str = Field(default_factory=generate_uuid, alias="_id")
    spec_id: str
    user_id: str

    # Change Request
    query: str
    nlp_confidence: Optional[float] = None

    # Changes Made
    diff: Dict[str, Any]
    spec_json: Dict[str, Any]
    changed_objects: Optional[str] = None

    # Preview & Cost
    preview_url: Optional[str] = Field(None, max_length=512)
    cost_delta: Optional[float] = None
    new_total_cost: Optional[float] = None

    # Metadata
    processing_time_ms: Optional[int] = None

    # Timestamps
    created_at: datetime = Field(default_factory=utc_now)

    class Config:
        populate_by_name = True


class Evaluation(BaseModel):
    """User feedback/ratings on designs"""

    id: Optional[str] = Field(default_factory=generate_uuid, alias="_id")
    spec_id: str
    user_id: str

    # Rating
    rating: float = Field(..., ge=0, le=5)
    notes: Optional[str] = None

    # Aspect Ratings
    aspects: Optional[Dict[str, float]] = None

    # Tags
    tags: Optional[List[str]] = None

    # Timestamps
    created_at: datetime = Field(default_factory=utc_now)

    class Config:
        populate_by_name = True


# ============================================================================
# COMPLIANCE MODELS
# ============================================================================


class ComplianceCheck(BaseModel):
    """Compliance verification results from Sohum's MCP"""

    id: str = Field(default_factory=generate_uuid, alias="_id")
    spec_id: str

    # External Reference
    case_id: Optional[str] = None

    # Check Details
    city: str = Field(..., max_length=50)
    case_type: str = Field(..., max_length=50)

    # Status
    status: str = "pending"

    # Results
    result: Optional[Dict[str, Any]] = None
    compliant: Optional[bool] = None
    confidence_score: Optional[float] = None

    # Violations
    violations: Optional[List[Dict[str, Any]]] = None
    recommendations: Optional[List[Dict[str, Any]]] = None

    # Geometry
    geometry_url: Optional[str] = Field(None, max_length=512)

    # Timestamps
    created_at: datetime = Field(default_factory=utc_now)
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None

    class Config:
        populate_by_name = True


# ============================================================================
# RL FEEDBACK MODELS
# ============================================================================


class RLFeedback(BaseModel):
    """Reinforcement learning feedback data"""

    id: Optional[str] = Field(default_factory=generate_uuid, alias="_id")
    user_id: str
    spec_id: Optional[str] = None

    # Input
    prompt: str
    context: Optional[Dict[str, Any]] = None

    # Output
    spec_json: Dict[str, Any]

    # Scores
    rl_score: Optional[float] = None
    user_rating: Optional[float] = None
    reward: Optional[float] = None

    # Feedback Type
    feedback_type: str = "implicit"  # implicit, explicit

    # Training
    used_for_training: bool = False
    training_batch_id: Optional[str] = None

    # Timestamps
    created_at: datetime = Field(default_factory=utc_now)

    class Config:
        populate_by_name = True


# ============================================================================
# VR RENDER MODELS
# ============================================================================


class VRRender(BaseModel):
    """VR rendering jobs and results"""

    id: str = Field(default_factory=generate_uuid, alias="_id")
    spec_id: str
    user_id: str

    # Render Settings
    quality: str = "high"
    resolution: Optional[str] = None

    # Status
    status: str = "queued"
    progress: int = 0

    # Output
    render_url: Optional[str] = Field(None, max_length=512)
    local_path: Optional[str] = Field(None, max_length=512)
    file_size_bytes: Optional[int] = None

    # Performance
    estimated_time_seconds: Optional[int] = None
    actual_time_seconds: Optional[int] = None

    # Error Handling
    error_message: Optional[str] = None
    retry_count: int = 0

    # Timestamps
    created_at: datetime = Field(default_factory=utc_now)
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None

    class Config:
        populate_by_name = True


# ============================================================================
# AUDIT & LOGGING MODELS
# ============================================================================


class AuditLog(BaseModel):
    """Audit trail for security and compliance"""

    id: Optional[str] = Field(default_factory=generate_uuid, alias="_id")

    # Actor
    user_id: Optional[str] = None

    # Action
    action: str = Field(..., max_length=100)
    resource_type: Optional[str] = Field(None, max_length=50)
    resource_id: Optional[str] = None

    # Details
    details: Optional[Dict[str, Any]] = None
    status: Optional[str] = None  # success, failure, error
    error_message: Optional[str] = None

    # Request Info
    ip_address: Optional[str] = Field(None, max_length=45)
    user_agent: Optional[str] = Field(None, max_length=255)
    request_id: Optional[str] = Field(None, max_length=50)

    # Timestamps
    created_at: datetime = Field(default_factory=utc_now)

    class Config:
        populate_by_name = True


# ============================================================================
# WORKFLOW TRACKING
# ============================================================================


class WorkflowRun(BaseModel):
    """Track Prefect workflow executions"""

    id: Optional[str] = Field(default_factory=generate_uuid, alias="_id")

    # Workflow Info
    flow_name: str = Field(..., max_length=100)
    flow_run_id: Optional[str] = Field(None, max_length=100)
    deployment_name: Optional[str] = Field(None, max_length=100)

    # Execution
    status: Optional[str] = None  # scheduled, running, completed, failed, cancelled
    parameters: Optional[Dict[str, Any]] = None
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None

    # Timestamps
    scheduled_at: Optional[datetime] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    duration_seconds: Optional[float] = None

    # Created
    created_at: datetime = Field(default_factory=utc_now)

    class Config:
        populate_by_name = True


# Export all models
__all__ = [
    "User",
    "RefreshToken",
    "Spec",
    "Iteration",
    "Evaluation",
    "ComplianceCheck",
    "RLFeedback",
    "VRRender",
    "AuditLog",
    "WorkflowRun",
]
