"""Generate validation report from validation_summary.json - ONLY Source of Truth

This is the ONLY way to generate validation reports.
Manual summary files are NOT allowed.
"""
import json
import sys
from datetime import datetime
from pathlib import Path

SUMMARY_FILE = Path("production_validation_results/validation_summary.json")
README_FILE = Path("production_validation_results/README.md")


def load_validation_data() -> dict:
    if not SUMMARY_FILE.exists():
        print(f"ERROR: {SUMMARY_FILE} not found. Run run_production_validation.py first.")
        sys.exit(1)
    with open(SUMMARY_FILE, encoding="utf-8") as f:
        data = json.load(f)
    if data.get("generated_by") != "run_production_validation.py":
        print("ERROR: validation_summary.json was not generated by run_production_validation.py. Refusing to report.")
        sys.exit(1)
    return data


def generate_report(data: dict) -> str:
    lines = [
        "=" * 70,
        "PRODUCTION VALIDATION REPORT",
        "=" * 70,
        f"Generated:      {datetime.now().isoformat()}",
        f"Source:         {SUMMARY_FILE}",
        f"Validation Run: {data['run_at']}",
        f"Status:         {data['status']}",
        f"Total Cases:    {data['total_cases']}",
        f"Passed:         {data['passed']}",
        f"Failed:         {data['failed']}",
        f"Pass Rate:      {data['pass_rate']}%",
        "",
        "CITY BREAKDOWN",
        "-" * 70,
    ]

    for city, city_data in data["results_by_city"].items():
        lines.append(f"{city}: {city_data['passed']}/{city_data['total']} passed")

    lines += ["", "DETAILED RESULTS", "-" * 70]
    for city, city_data in data["results_by_city"].items():
        for r in city_data["cases"]:
            status_marker = "PASS" if r["status"] == "passed" else "FAIL"
            lines.append(
                f"  {status_marker} {r['spec_id']}  {r['latency_ms']}ms  trace={r['trace_id'][:32] if r['trace_id'] else 'none'}"
            )
            if r.get("error"):
                lines.append(f"      ERROR: {r['error'][:120]}")

    return "\n".join(lines)


def update_readme(data: dict) -> None:
    if not README_FILE.exists():
        return
    content = README_FILE.read_text(encoding="utf-8")
    if data["status"] == "VALIDATED":
        content = content.replace(
            "## Status: NOT VALIDATED",
            f"## Status: VALIDATED\n\nLast run: {data['run_at']}  "
            f"Passed: {data['passed']}/{data['total_cases']} ({data['pass_rate']}%)",
        )
    elif "## Status: NOT VALIDATED" not in content:
        pass  # already updated
    README_FILE.write_text(content, encoding="utf-8")
    print(f"README updated: {README_FILE}")


if __name__ == "__main__":
    data = load_validation_data()
    report = generate_report(data)
    sys.stdout.buffer.write(report.encode("utf-8"))
    sys.stdout.buffer.write(b"\n")

    output_file = Path("production_validation_results/REPORT.txt")
    output_file.write_text(report, encoding="utf-8")
    sys.stdout.buffer.write(f"\nReport saved: {output_file}\n".encode("utf-8"))

    update_readme(data)
