"""
History API - retrieves previously generated design specs from MongoDB.
"""
import logging
from typing import Optional

from app.auth_mongodb import get_current_user
from fastapi import APIRouter, Depends, HTTPException, Query

router = APIRouter()
logger = logging.getLogger(__name__)


@router.get("/history")
async def get_user_history(
    current_user: str = Depends(get_current_user),
    limit: int = Query(20, ge=1, le=100, description="Max specs to return"),
    skip: int = Query(0, ge=0, description="Number of specs to skip"),
):
    """Return all specs generated by the current user, newest first."""
    try:
        from app.database_mongodb import get_database
        db = get_database()
    except RuntimeError:
        raise HTTPException(status_code=503, detail="Database unavailable")

    try:
        cursor = (
            db.specs
            .find({"user_id": current_user})
            .sort("created_at", -1)
            .skip(skip)
            .limit(limit)
        )
        specs = await cursor.to_list(length=limit)
        total = await db.specs.count_documents({"user_id": current_user})
    except Exception as e:
        logger.error("MongoDB query failed for user %s: %s", current_user, e)
        raise HTTPException(status_code=500, detail="Failed to retrieve history")

    specs_data = []
    for spec in specs:
        spec_json = spec.get("spec_json") or {}
        created_at = spec.get("created_at")
        specs_data.append({
            "spec_id": spec.get("_id"),
            "prompt": spec.get("prompt"),
            "city": spec.get("city"),
            "design_type": spec.get("design_type") or spec_json.get("design_type"),
            "estimated_cost": spec.get("estimated_cost"),
            "currency": spec.get("currency", "INR"),
            "status": spec.get("status", "final"),
            "compliance_status": spec.get("compliance_status", "pending"),
            "preview_url": spec.get("preview_url") or spec.get("geometry_url"),
            "lm_provider": spec.get("lm_provider"),
            "version": spec.get("version", 1),
            "created_at": created_at.isoformat() if hasattr(created_at, "isoformat") else str(created_at) if created_at else None,
            "has_spec_json": bool(spec_json),
        })

    return {
        "user_id": current_user,
        "specs": specs_data,
        "total_specs": total,
        "returned": len(specs_data),
        "skip": skip,
        "limit": limit,
    }


@router.get("/history/{spec_id}")
async def get_spec_history(
    spec_id: str,
    current_user: str = Depends(get_current_user),
):
    """Return a single spec by ID (must belong to the current user)."""
    try:
        from app.database_mongodb import get_database
        db = get_database()
    except RuntimeError:
        raise HTTPException(status_code=503, detail="Database unavailable")

    try:
        spec = await db.specs.find_one({"_id": spec_id, "user_id": current_user})
    except Exception as e:
        logger.error("MongoDB query failed for spec %s: %s", spec_id, e)
        raise HTTPException(status_code=500, detail="Database error")

    if not spec:
        raise HTTPException(status_code=404, detail=f"Spec '{spec_id}' not found")

    spec_json = spec.get("spec_json") or {}
    created_at = spec.get("created_at")

    return {
        "spec_id": spec.get("_id"),
        "user_id": spec.get("user_id"),
        "prompt": spec.get("prompt"),
        "city": spec.get("city"),
        "design_type": spec.get("design_type") or spec_json.get("design_type"),
        "spec_json": spec_json,
        "estimated_cost": spec.get("estimated_cost"),
        "currency": spec.get("currency", "INR"),
        "status": spec.get("status", "final"),
        "compliance_status": spec.get("compliance_status", "pending"),
        "preview_url": spec.get("preview_url") or spec.get("geometry_url"),
        "lm_provider": spec.get("lm_provider"),
        "version": spec.get("version", 1),
        "created_at": created_at.isoformat() if hasattr(created_at, "isoformat") else str(created_at) if created_at else None,
    }
