"""
Unit tests for TTGPayloadBuilder.
All tests are pure — no HTTP, no filesystem reads after import.
"""

import pytest
from app.adapters.ttg_payload_builder import (
    _DOMAIN_GENERATOR,
    _DOMAIN_OUTPUT_FORMATS,
    _DOMAIN_SCHEMA_TYPE,
    PAYLOAD_SCHEMA_VERSION,
    TTGExecutePayload,
    TTGPayloadBuilder,
    TTGPayloadError,
)

# ── Fixtures ──────────────────────────────────────────────────────────────────

BUCKET_URLS = ["https://bhiv-bucket.onrender.com/bucket/artifact/abc123"]

SPEC_JSON = {
    "type": "drone",
    "dimensions": {"width": 0.8, "length": 0.8, "height": 0.3},
    "components": ["frame", "rotor", "motor", "battery"],
    "units": "meters",
}

METADATA = {
    "prompt": "Generate a cargo drone",
    "intent": "design_creation",
    "product_context": "creator_core",
    "output_format": "step_by_step_guide",
}

SEMANTIC = {
    "vehicle": {
        "domain": "vehicle",
        "entity": "drone",
        "generation_mode": "mesh",
        "geometry_family": "rotorcraft",
    },
    "architecture": {
        "domain": "architecture",
        "entity": "2bhk",
        "generation_mode": "layout",
        "geometry_family": "apartment_layout",
    },
    "object": {
        "domain": "object",
        "entity": "crate",
        "generation_mode": "mesh",
        "geometry_family": "primitive_prop",
    },
    "environment": {
        "domain": "environment",
        "entity": "forest",
        "generation_mode": "grouped_geometry",
        "geometry_family": "vegetation_zone",
    },
    "gameplay": {
        "domain": "gameplay",
        "entity": "obstacle",
        "generation_mode": "mesh",
        "geometry_family": "gameplay_prop",
    },
    "gameplay_trigger": {
        "domain": "gameplay",
        "entity": "spawn_point",
        "generation_mode": "trigger_volume",
        "geometry_family": "logic_marker",
    },
}


def build(domain: str = "vehicle", **overrides) -> TTGExecutePayload:
    """Helper — build a payload for a given domain with optional overrides."""
    builder = TTGPayloadBuilder()
    kwargs = dict(
        semantic_resolution=SEMANTIC[domain],
        spec_json=SPEC_JSON,
        bucket_urls=BUCKET_URLS,
        trace_id="trace_test_001",
        execution_id="exec_test_001",
        metadata=METADATA,
    )
    kwargs.update(overrides)
    return builder.build(**kwargs)


# ══════════════════════════════════════════════════════════════════════════════
# 1. Output structure — TTGExecutePayload shape
# ══════════════════════════════════════════════════════════════════════════════


class TestOutputStructure:
    def test_returns_ttg_execute_payload_instance(self):
        assert isinstance(build(), TTGExecutePayload)

    def test_execution_id_propagated(self):
        p = build(execution_id="exec_custom_99")
        assert p.execution_id == "exec_custom_99"

    def test_execution_id_autogenerated_when_none(self):
        builder = TTGPayloadBuilder()
        p = builder.build(
            semantic_resolution=SEMANTIC["vehicle"],
            spec_json=SPEC_JSON,
            bucket_urls=BUCKET_URLS,
            trace_id="trace_001",
        )
        assert p.execution_id.startswith("exec_")

    def test_trace_id_propagated(self):
        p = build(trace_id="trace_custom_abc")
        assert p.trace_id == "trace_custom_abc"

    def test_spec_json_preserved_exactly(self):
        p = build()
        assert p.spec_json == SPEC_JSON

    def test_bucket_urls_preserved(self):
        p = build()
        assert p.bucket_urls == BUCKET_URLS

    def test_asset_refs_defaults_to_empty_list(self):
        p = build()
        assert p.asset_refs == []

    def test_asset_refs_propagated_when_provided(self):
        refs = ["https://bhiv-bucket.onrender.com/bucket/artifact/ref001"]
        p = build(asset_refs=refs)
        assert p.asset_refs == refs

    def test_to_dict_contains_all_six_required_keys(self):
        d = build().to_dict()
        for key in ("execution_id", "trace_id", "executionSchema", "spec_json", "asset_refs", "bucket_urls"):
            assert key in d, f"Missing key: {key}"

    def test_to_full_dict_contains_meta_block(self):
        fd = build().to_full_dict()
        assert "_meta" in fd
        assert "domain" in fd["_meta"]
        assert "schema_type" in fd["_meta"]
        assert "output_formats" in fd["_meta"]

    def test_domain_field_populated(self):
        assert build("vehicle").domain == "vehicle"
        assert build("architecture").domain == "architecture"

    def test_schema_type_matches_domain_table(self):
        for domain in ("vehicle", "architecture", "object", "environment", "gameplay"):
            p = build(domain)
            assert p.schema_type == _DOMAIN_SCHEMA_TYPE[domain]

    def test_output_formats_match_domain_table(self):
        for domain in ("vehicle", "architecture", "object", "environment", "gameplay"):
            p = build(domain)
            assert p.output_formats == _DOMAIN_OUTPUT_FORMATS[domain]

    def test_multiple_bucket_urls_preserved(self):
        urls = [
            "https://bhiv-bucket.onrender.com/bucket/artifact/abc",
            "https://bhiv-bucket.onrender.com/bucket/artifact/def",
            "https://bhiv-bucket.onrender.com/bucket/artifact/ghi",
        ]
        p = build(bucket_urls=urls)
        assert p.bucket_urls == urls


# ══════════════════════════════════════════════════════════════════════════════
# 2. executionSchema — per domain
# ══════════════════════════════════════════════════════════════════════════════


class TestExecutionSchemaVehicle:
    def setup_method(self):
        self.schema = build("vehicle").executionSchema

    def test_schema_type_is_mesh(self):
        assert self.schema["schema_type"] == "mesh"

    def test_domain_is_vehicle(self):
        assert self.schema["domain"] == "vehicle"

    def test_entity_is_drone(self):
        assert self.schema["entity"] == "drone"

    def test_generation_mode_is_mesh(self):
        assert self.schema["generation_mode"] == "mesh"

    def test_geometry_family_is_rotorcraft(self):
        assert self.schema["geometry_family"] == "rotorcraft"

    def test_generator_is_mesh_generator(self):
        assert self.schema["generator"] == "mesh_generator"

    def test_schema_version_present(self):
        assert self.schema["schema_version"] == PAYLOAD_SCHEMA_VERSION

    def test_mesh_config_present(self):
        assert "mesh_config" in self.schema

    def test_mesh_config_units_meters(self):
        assert self.schema["mesh_config"]["units"] == "meters"

    def test_output_formats_present(self):
        assert "glb" in self.schema["output_formats"]
        assert "stl" in self.schema["output_formats"]
        assert "step" in self.schema["output_formats"]


class TestExecutionSchemaArchitecture:
    def setup_method(self):
        self.schema = build("architecture").executionSchema

    def test_schema_type_is_layout(self):
        assert self.schema["schema_type"] == "scene/layout"

    def test_domain_is_architecture(self):
        assert self.schema["domain"] == "architecture"

    def test_generator_is_layout_generator(self):
        assert self.schema["generator"] == "layout_generator"

    def test_layout_config_present(self):
        assert "layout_config" in self.schema

    def test_wall_thickness_enforced(self):
        assert self.schema["layout_config"]["enforce_wall_thickness"] is True

    def test_room_separation_enforced(self):
        assert self.schema["layout_config"]["room_separation"] is True

    def test_door_gaps_enforced(self):
        assert self.schema["layout_config"]["door_gaps"] is True


class TestExecutionSchemaObject:
    def setup_method(self):
        self.schema = build("object").executionSchema

    def test_schema_type_is_reusable_asset(self):
        assert self.schema["schema_type"] == "reusable_asset"

    def test_asset_config_reusable_true(self):
        assert self.schema["asset_config"]["reusable"] is True

    def test_asset_config_origin_centered(self):
        assert self.schema["asset_config"]["origin_centered"] is True

    def test_generator_is_mesh_generator(self):
        assert self.schema["generator"] == "mesh_generator"


class TestExecutionSchemaEnvironment:
    def setup_method(self):
        self.schema = build("environment").executionSchema

    def test_schema_type_is_zone(self):
        assert self.schema["schema_type"] == "zone"

    def test_generator_is_grouped_geometry(self):
        assert self.schema["generator"] == "grouped_geometry_generator"

    def test_zone_config_instancing_enabled(self):
        assert self.schema["zone_config"]["instancing_enabled"] is True

    def test_zone_config_lod_levels(self):
        assert self.schema["zone_config"]["lod_levels"] == 2


class TestExecutionSchemaGameplay:
    def setup_method(self):
        self.schema = build("gameplay").executionSchema

    def test_schema_type_is_gameplay(self):
        assert self.schema["schema_type"] == "gameplay"

    def test_generator_is_mixed_generator(self):
        assert self.schema["generator"] == "mixed_generator"

    def test_gameplay_config_collision_enabled(self):
        assert self.schema["gameplay_config"]["collision_enabled"] is True

    def test_intent_compile_bypassed_is_true(self):
        # CRITICAL: /api/intent/compile must never be called for gameplay domain
        # SemanticResolver is the semantic authority
        assert self.schema["intent_compile_bypassed"] is True

    def test_trigger_volume_false_for_mesh_mode(self):
        assert self.schema["gameplay_config"]["trigger_zones"] is False

    def test_trigger_volume_true_for_trigger_mode(self):
        schema = build("gameplay_trigger").executionSchema
        assert schema["gameplay_config"]["trigger_zones"] is True


# ══════════════════════════════════════════════════════════════════════════════
# 3. Validation — fail-closed behaviour
# ══════════════════════════════════════════════════════════════════════════════


class TestValidationFailClosed:
    def test_unknown_domain_raises_payload_error(self):
        bad_semantic = {**SEMANTIC["vehicle"], "domain": "spaceship"}
        with pytest.raises(TTGPayloadError) as exc_info:
            TTGPayloadBuilder().build(
                semantic_resolution=bad_semantic,
                spec_json=SPEC_JSON,
                bucket_urls=BUCKET_URLS,
                trace_id="trace_001",
            )
        assert exc_info.value.error_code == "TTG_UNKNOWN_DOMAIN"

    def test_empty_domain_raises_payload_error(self):
        bad_semantic = {**SEMANTIC["vehicle"], "domain": ""}
        with pytest.raises(TTGPayloadError) as exc_info:
            TTGPayloadBuilder().build(
                semantic_resolution=bad_semantic,
                spec_json=SPEC_JSON,
                bucket_urls=BUCKET_URLS,
                trace_id="trace_001",
            )
        assert exc_info.value.error_code in ("TTG_MISSING_SEMANTIC_KEY", "TTG_UNKNOWN_DOMAIN")

    def test_missing_entity_raises_payload_error(self):
        bad = {k: v for k, v in SEMANTIC["vehicle"].items() if k != "entity"}
        with pytest.raises(TTGPayloadError) as exc_info:
            TTGPayloadBuilder().build(
                semantic_resolution=bad,
                spec_json=SPEC_JSON,
                bucket_urls=BUCKET_URLS,
                trace_id="trace_001",
            )
        assert exc_info.value.error_code == "TTG_MISSING_SEMANTIC_KEY"

    def test_missing_generation_mode_raises(self):
        bad = {k: v for k, v in SEMANTIC["vehicle"].items() if k != "generation_mode"}
        with pytest.raises(TTGPayloadError) as exc_info:
            TTGPayloadBuilder().build(
                semantic_resolution=bad,
                spec_json=SPEC_JSON,
                bucket_urls=BUCKET_URLS,
                trace_id="trace_001",
            )
        assert exc_info.value.error_code == "TTG_MISSING_SEMANTIC_KEY"

    def test_missing_geometry_family_raises(self):
        bad = {k: v for k, v in SEMANTIC["vehicle"].items() if k != "geometry_family"}
        with pytest.raises(TTGPayloadError) as exc_info:
            TTGPayloadBuilder().build(
                semantic_resolution=bad,
                spec_json=SPEC_JSON,
                bucket_urls=BUCKET_URLS,
                trace_id="trace_001",
            )
        assert exc_info.value.error_code == "TTG_MISSING_SEMANTIC_KEY"

    def test_empty_spec_json_raises(self):
        with pytest.raises(TTGPayloadError) as exc_info:
            TTGPayloadBuilder().build(
                semantic_resolution=SEMANTIC["vehicle"],
                spec_json={},
                bucket_urls=BUCKET_URLS,
                trace_id="trace_001",
            )
        assert exc_info.value.error_code == "TTG_INVALID_SPEC_JSON"

    def test_non_dict_spec_json_raises(self):
        with pytest.raises(TTGPayloadError) as exc_info:
            TTGPayloadBuilder().build(
                semantic_resolution=SEMANTIC["vehicle"],
                spec_json="not a dict",  # type: ignore
                bucket_urls=BUCKET_URLS,
                trace_id="trace_001",
            )
        assert exc_info.value.error_code == "TTG_INVALID_SPEC_JSON"

    def test_empty_bucket_urls_raises(self):
        with pytest.raises(TTGPayloadError) as exc_info:
            TTGPayloadBuilder().build(
                semantic_resolution=SEMANTIC["vehicle"],
                spec_json=SPEC_JSON,
                bucket_urls=[],
                trace_id="trace_001",
            )
        assert exc_info.value.error_code == "TTG_MISSING_BUCKET_URLS"

    def test_bucket_url_empty_string_raises(self):
        with pytest.raises(TTGPayloadError) as exc_info:
            TTGPayloadBuilder().build(
                semantic_resolution=SEMANTIC["vehicle"],
                spec_json=SPEC_JSON,
                bucket_urls=[""],
                trace_id="trace_001",
            )
        assert exc_info.value.error_code == "TTG_INVALID_BUCKET_URL"

    def test_empty_trace_id_raises(self):
        with pytest.raises(TTGPayloadError) as exc_info:
            TTGPayloadBuilder().build(
                semantic_resolution=SEMANTIC["vehicle"],
                spec_json=SPEC_JSON,
                bucket_urls=BUCKET_URLS,
                trace_id="",
            )
        assert exc_info.value.error_code == "TTG_MISSING_TRACE_ID"

    def test_whitespace_trace_id_raises(self):
        with pytest.raises(TTGPayloadError) as exc_info:
            TTGPayloadBuilder().build(
                semantic_resolution=SEMANTIC["vehicle"],
                spec_json=SPEC_JSON,
                bucket_urls=BUCKET_URLS,
                trace_id="   ",
            )
        assert exc_info.value.error_code == "TTG_MISSING_TRACE_ID"


# ══════════════════════════════════════════════════════════════════════════════
# 4. Metadata propagation
# ══════════════════════════════════════════════════════════════════════════════


class TestMetadataPropagation:
    def test_metadata_in_execution_schema(self):
        p = build(metadata=METADATA)
        assert p.executionSchema["pipeline_metadata"] == METADATA

    def test_empty_metadata_defaults_to_empty_dict(self):
        p = build(metadata=None)
        assert p.executionSchema["pipeline_metadata"] == {}

    def test_metadata_does_not_pollute_spec_json(self):
        p = build(metadata=METADATA)
        assert "pipeline_metadata" not in p.spec_json
        assert "prompt" not in p.spec_json


# ══════════════════════════════════════════════════════════════════════════════
# 5. Exception hierarchy
# ══════════════════════════════════════════════════════════════════════════════


class TestExceptionHierarchy:
    def test_ttg_payload_error_is_exception(self):
        assert issubclass(TTGPayloadError, Exception)

    def test_ttg_payload_error_stores_code(self):
        err = TTGPayloadError("test", error_code="TTG_TEST_CODE")
        assert err.error_code == "TTG_TEST_CODE"

    def test_default_error_code(self):
        err = TTGPayloadError("test")
        assert err.error_code == "TTG_PAYLOAD_ERROR"


# ══════════════════════════════════════════════════════════════════════════════
# 6. All 5 domains build without error
# ══════════════════════════════════════════════════════════════════════════════


class TestAllDomainsSucceed:
    @pytest.mark.parametrize("domain", ["vehicle", "architecture", "object", "environment", "gameplay"])
    def test_domain_builds_successfully(self, domain):
        p = build(domain)
        assert isinstance(p, TTGExecutePayload)
        assert p.domain == domain
        assert p.execution_id
        assert p.trace_id
        assert p.executionSchema
        assert p.spec_json
        assert p.bucket_urls

    @pytest.mark.parametrize("domain", ["vehicle", "architecture", "object", "environment", "gameplay"])
    def test_to_dict_is_serialisable(self, domain):
        import json

        d = build(domain).to_dict()
        # Should not raise
        json.dumps(d)

    @pytest.mark.parametrize("domain", ["vehicle", "architecture", "object", "environment", "gameplay"])
    def test_execution_schema_has_schema_type(self, domain):
        p = build(domain)
        assert p.executionSchema["schema_type"] == _DOMAIN_SCHEMA_TYPE[domain]

    @pytest.mark.parametrize("domain", ["vehicle", "architecture", "object", "environment", "gameplay"])
    def test_execution_schema_has_generator(self, domain):
        p = build(domain)
        assert p.executionSchema["generator"] == _DOMAIN_GENERATOR[domain]


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
